sonata_admin:
    title: 'Blog Admin'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            default: ~
            security:
                label: Security
                label_catalogue: ~
                items:
                    - route: security_logout
                      label: Logout

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
